project_id = "rljnrgscmosgkcjdvlrq"

[functions.chat-completions]
verify_jwt = false

[functions.process-dataset]
verify_jwt = false

[functions.generate-synthetic]
verify_jwt = false

[functions.run-evaluation]
verify_jwt = false

[functions.webhook-finetuning]
verify_jwt = false
