project_id = "rljnrgscmosgkcjdvlrq"

[functions.chat-completions]
verify_jwt = true

[functions.process-dataset]
verify_jwt = false

[functions.generate-synthetic]
verify_jwt = false

[functions.run-evaluation]
verify_jwt = false

[functions.webhook-finetuning]
verify_jwt = false

[functions.start-finetuning]
verify_jwt = true

[functions.create-credits-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.import-huggingface]
verify_jwt = true

[functions.embed-document]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.slack-oauth]
verify_jwt = false

[functions.slack-sync]
verify_jwt = true

[functions.notion-oauth]
verify_jwt = false

[functions.notion-sync]
verify_jwt = true

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = true

[functions.github-oauth]
verify_jwt = false

[functions.github-sync]
verify_jwt = true

[functions.search-documents]
verify_jwt = true

[functions.keep-modal-warm]
verify_jwt = false

[functions.import-url]
verify_jwt = true
