apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helios-ingress
spec:
  tls:
  - hosts:
    - health-staging.swissbrain.ai
    secretName: helios-staging-tls
  rules:
  - host: health-staging.swissbrain.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: staging-helios-api
            port:
              number: 80
