apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helios-staging

resources:
- ../../base

namePrefix: staging-

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

configMapGenerator:
- name: helios-config
  behavior: merge
  literals:
  - NODE_ENV=staging
  - LOG_LEVEL=debug

images:
- name: registry.exoscale.com/axessible/helios
  newTag: staging
