apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helios

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml

configMapGenerator:
- name: helios-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=warn
  - RATE_LIMIT_REQUESTS=200

images:
- name: registry.exoscale.com/axessible/helios
  newTag: v1.0.0
